# Docker Compose configuration for MCP Server
# This is a separate file to allow independent building and deployment of the MCP server
# 
# Usage:
#   docker compose -f docker-compose.mcp.yml build
#   docker compose -f docker-compose.mcp.yml up -d

services:
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    image: legacy-use-mcp-server:local
    container_name: legacy-use-mcp-server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@demo-db:5432/legacy_use_demo
      - LEGACY_USE_URL=http://legacy-use-mgmt:8088
      - LEGACY_USE_API_KEY=${LEGACY_USE_API_KEY:-}
      - LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - SYNC_INTERVAL=${MCP_SYNC_INTERVAL:-30}
    env_file:
      - .env
      - .env.local
    restart: unless-stopped
    networks:
      - legacy-use-network

networks:
  legacy-use-network:
    external: true
    name: legacy-use_legacy-use-network