services:
  # Main legacy-use management service
  legacy-use-mgmt:
    image: legacy-use-mgmt:local
    container_name: legacy-use-mgmt
    environment:
      - LEGACY_USE_DEBUG=${LEGACY_USE_DEBUG:-0}
      - DATABASE_URL=postgresql://postgres:postgres@demo-db:5432/legacy_use_demo
      - CONTAINER_ORCHESTRATOR=docker
    env_file:
      - .env
      - .env.local
    ports:
      - "8088:8088"
      - "5173:5173"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Development mode volumes (only when LEGACY_USE_DEBUG=1)
      - ./server:/home/legacy-use-mgmt/server/
      - ./app:/home/legacy-use-mgmt/app/
    depends_on:
      - demo-db
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Demo database
  demo-db:
    image: legacy-use-demo-db:local
    container_name: legacy-use-demo-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legacy_use_demo
    volumes:
      - demo_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Wine target for Windows application support
  wine-target:
    image: legacy-use-wine-target:local
    labels:
      - "legacy-use.target-type=wine"
      - "legacy-use.scalable=true"
    environment:
      - DISPLAY=:1
      - WINEARCH=win64
      - WINEPREFIX=/home/wineuser/.wine
    ports:
      - "5900:5900"  # VNC
    volumes:
      - wine_data:/home/wineuser/.wine
      - wine_apps:/home/wineuser/apps
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Linux machine target (example target)
  linux-machine:
    image: linux-machine:local
    labels:
      - "legacy-use.target-type=linux"
      - "legacy-use.scalable=true"
    ports:
      - "5901:5900"  # VNC (different port to avoid Wine conflict)
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Android emulator target
  android-target:
    image: legacy-use-android-target:local
    labels:
      - "legacy-use.target-type=android"
      - "legacy-use.scalable=true"
    privileged: true
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    ports:
      - "5555:5555"  # ADB
      - "5902:5900"  # VNC (different port to avoid conflicts)
      # Note: Android target still has built-in noVNC, but we use shared proxy instead
    volumes:
      - android_data:/home/androidusr/.android
      - android_apps:/home/androidusr/apps
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Shared noVNC proxy for all VNC connections
  novnc-proxy:
    image: legacy-use-novnc-proxy:local
    container_name: legacy-use-novnc-proxy
    environment:
      - LEGACY_USE_URL=http://legacy-use-mgmt:8088
      - API_KEY=${API_KEY:-not-secure-api-key}
    ports:
      - "6090:80"  # Different port to avoid conflicts
    depends_on:
      - legacy-use-mgmt
    restart: unless-stopped
    networks:
      - legacy-use-network

  # MCP server for API integration
  mcp-server:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-mcp/Dockerfile
    image: legacy-use-mcp-server:local
    container_name: legacy-use-mcp-server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@demo-db:5432/legacy_use_demo
      - LEGACY_USE_URL=http://legacy-use-mgmt:8088
      - LEGACY_USE_API_KEY=${LEGACY_USE_API_KEY:-}
      - LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - SYNC_INTERVAL=${MCP_SYNC_INTERVAL:-30}
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=3000
      - MCP_SERVER_PATH=/mcp
    env_file:
      - .env
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - demo-db
      - legacy-use-mgmt
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Optional: Windows VM target (requires KVM)
  # Uncomment if you want to use full Windows VM
  # windows-target:
  #   image: dockurr/windows:latest
  #   container_name: legacy-use-windows-target
  #   environment:
  #     - VERSION=11
  #     - DISK_SIZE=64G
  #     - RAM_SIZE=8G
  #     - CPU_CORES=4
  #     - USERNAME=LegacyUser
  #     - PASSWORD=LegacyPass123!
  #   ports:
  #     - "8006:8006"  # Web viewer
  #     - "3389:3389"  # RDP
  #   volumes:
  #     - windows_data:/storage
  #   devices:
  #     - /dev/kvm:/dev/kvm
  #   cap_add:
  #     - NET_ADMIN
  #   restart: unless-stopped
  #   networks:
  #     - legacy-use-network

volumes:
  demo_db_data:
  wine_data:
  wine_apps:
  android_data:
  android_apps:
  # windows_data:

networks:
  legacy-use-network:
    driver: bridge