# Kind cluster configuration with local registry and KubeVirt support
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Configure registry for all nodes
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
nodes:
  # Control plane node
  - role: control-plane
    # KubeVirt needs access to /dev for device plugins
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
      - hostPath: /boot
        containerPath: /boot
        readOnly: true
      - hostPath: /lib/modules
        containerPath: /lib/modules
        readOnly: true
  # Worker node for running VMs
  - role: worker
    extraMounts:
      - hostPath: /dev
        containerPath: /dev
      - hostPath: /boot
        containerPath: /boot
        readOnly: true
      - hostPath: /lib/modules
        containerPath: /lib/modules
        readOnly: true
# Networking configuration
networking:
  # Use the default CNI (kindnet)
  disableDefaultCNI: false
  # Custom API server port to avoid conflicts
  apiServerPort: 6443
# Feature gates for KubeVirt compatibility
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        # Enable features needed by KubeVirt
        feature-gates: "KubeletInUserNamespace=true"
        # Increase max pods per node for VM workloads
        max-pods: "110"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        # Enable features needed by KubeVirt
        feature-gates: "KubeletInUserNamespace=true"