apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "legacy-use.fullname" . }}-config
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
data:
  LEGACY_USE_DEBUG: {{ .Values.backend.env.LEGACY_USE_DEBUG | quote }}
  {{- if .Values.backend.env.DATABASE_URL }}
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  {{- end }}
