{{- if .Values.mcpServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legacy-use.fullname" . }}-mcp-server
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  replicas: {{ .Values.mcpServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "legacy-use.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      labels:
        {{- include "legacy-use.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legacy-use.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.mcpServer.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp-server
          securityContext:
            {{- toYaml .Values.mcpServer.securityContext | nindent 12 }}
          image: "{{ .Values.mcpServer.image.repository }}:{{ .Values.mcpServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mcpServer.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ include "legacy-use.fullname" . }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}"
            - name: LEGACY_USE_URL
              value: "http://{{ include "legacy-use.fullname" . }}-backend:{{ .Values.backend.service.port }}"
            - name: LEGACY_USE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "legacy-use.fullname" . }}-api-key
                  key: api-key
                  optional: true
            - name: LOG_LEVEL
              value: {{ .Values.mcpServer.logLevel | quote }}
            - name: SYNC_INTERVAL
              value: {{ .Values.mcpServer.syncInterval | quote }}
            {{- with .Values.mcpServer.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.mcpServer.resources | nindent 12 }}
      {{- with .Values.mcpServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mcpServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}