{{- if .Values.windowsTarget.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-target
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-target
spec:
  type: {{ .Values.windowsTarget.service.type }}
  ports:
    - port: 8006
      targetPort: web
      protocol: TCP
      name: web
    - port: 3389
      targetPort: rdp
      protocol: TCP
      name: rdp
    - port: 5900
      targetPort: vnc
      protocol: TCP
      name: vnc
    - port: 6080
      targetPort: novnc
      protocol: TCP
      name: novnc
  selector:
    app.kubernetes.io/name: {{ include "legacy-use.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: windows-target
{{- end }}