{{- if .Values.androidTarget.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legacy-use.fullname" . }}-android-target
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: android-target
spec:
  replicas: {{ .Values.androidTarget.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "legacy-use.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: android-target
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "legacy-use.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: android-target
        {{- with .Values.androidTarget.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legacy-use.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.androidTarget.podSecurityContext | nindent 8 }}
      containers:
        - name: android
          securityContext:
            {{- toYaml .Values.androidTarget.securityContext | nindent 12 }}
          image: "{{ .Values.androidTarget.image.repository }}:{{ .Values.androidTarget.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.androidTarget.image.pullPolicy }}
          env:
            - name: EMULATOR_DEVICE
              value: "{{ .Values.androidTarget.emulatorDevice }}"
            - name: WEB_VNC
              value: "{{ .Values.androidTarget.webVnc }}"
          ports:
            - name: adb
              containerPort: 5555
              protocol: TCP
            - name: vnc
              containerPort: 5900
              protocol: TCP
            - name: novnc
              containerPort: 6080
              protocol: TCP
          volumeMounts:
            - name: android-data
              mountPath: /home/androidusr/.android
            - name: android-apps
              mountPath: /home/androidusr/apps
          resources:
            {{- toYaml .Values.androidTarget.resources | nindent 12 }}
      volumes:
        - name: android-data
          {{- if .Values.androidTarget.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "legacy-use.fullname" . }}-android-data
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: android-apps
          {{- if .Values.androidTarget.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "legacy-use.fullname" . }}-android-apps
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.androidTarget.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.androidTarget.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.androidTarget.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}