apiVersion: v1
kind: Service
metadata:
  name: {{ include "legacy-use.fullname" . }}-mgmt
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.backendPort }}
      targetPort: backend
      protocol: TCP
      name: backend
    - port: {{ .Values.management.service.frontendPort }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    {{- include "legacy-use.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: management