{{- if .Values.linuxTarget.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "legacy-use.fullname" . }}-linux-target
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: linux-target
spec:
  type: {{ .Values.linuxTarget.service.type }}
  ports:
    - port: {{ .Values.linuxTarget.service.vncPort }}
      targetPort: vnc
      protocol: TCP
      name: vnc
    - port: {{ .Values.linuxTarget.service.novncPort }}
      targetPort: novnc
      protocol: TCP
      name: novnc
  selector:
    app.kubernetes.io/name: {{ include "legacy-use.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: linux-target
{{- end }}