{{- if .Values.linuxTarget.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legacy-use.fullname" . }}-linux-target
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: linux-target
spec:
  replicas: {{ .Values.linuxTarget.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "legacy-use.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: linux-target
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "legacy-use.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: linux-target
        {{- with .Values.linuxTarget.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legacy-use.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.linuxTarget.podSecurityContext | nindent 8 }}
      containers:
        - name: linux-machine
          securityContext:
            {{- toYaml .Values.linuxTarget.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.linuxTarget.image.repository }}:{{ .Values.linuxTarget.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.linuxTarget.image.pullPolicy }}
          ports:
            - name: vnc
              containerPort: 5900
              protocol: TCP
          resources:
            {{- toYaml .Values.linuxTarget.resources | nindent 12 }}
      {{- with .Values.linuxTarget.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.linuxTarget.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.linuxTarget.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}