{{- if .Values.macosMojaveKubevirt.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "legacy-use.fullname" . }}-macos-info
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: macos-mojave-kubevirt
data:
  # Instructions for enabling macOS support
  README.md: |
    # macOS on KubeVirt
    
    This deployment uses a custom virt-launcher image that adds the Apple SMC device
    required for macOS to boot. The custom image wraps the standard virt-launcher
    and automatically injects the following when it detects a macOS VM:
    
    ```
    -device isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc
    ```
    
    ## How it works
    
    1. The custom virt-launcher image (virt-launcher-macos) contains a wrapper script
    2. The wrapper detects macOS VMs by looking for OVMF firmware or OpenCore bootloader
    3. When detected, it adds the Apple SMC device to the QEMU command line
    4. The VM is launched with full macOS compatibility
    
    ## Requirements
    
    - OVMF UEFI firmware images
    - OpenCore bootloader
    - macOS disk image
    - Sufficient CPU and memory resources
{{- end }}