{{- if .Values.mcpServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "legacy-use.fullname" . }}-mcp-server
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: http
      protocol: TCP
      name: mcp
  selector:
    {{- include "legacy-use.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
{{- end }}