{{- if .Values.novncProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "legacy-use.fullname" . }}-novnc-proxy
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: novnc-proxy
spec:
  replicas: {{ .Values.novncProxy.replicas }}
  selector:
    matchLabels:
      {{- include "legacy-use.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: novnc-proxy
  template:
    metadata:
      labels:
        {{- include "legacy-use.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: novnc-proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "legacy-use.serviceAccountName" . }}
      containers:
        - name: novnc-proxy
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.novncProxy.image.repository }}:{{ .Values.novncProxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.novncProxy.image.pullPolicy }}
          env:
            - name: LEGACY_USE_URL
              value: "http://{{ include "legacy-use.fullname" . }}-mgmt:{{ .Values.management.service.backendPort }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.management.existingSecret }}
                  key: api-key
                  optional: true
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.novncProxy.resources | nindent 12 }}
      {{- with .Values.novncProxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.novncProxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.novncProxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}