{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legacy-use.fullname" . }}-secrets
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.database.enabled .Values.database.existingSecret }}
# Database secret is expected to be created externally
{{- else if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legacy-use.fullname" . }}-database-secret
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.database.postgresPassword | b64enc | quote }}
  postgres-user: {{ .Values.database.postgresUser | b64enc | quote }}
  postgres-database: {{ .Values.database.postgresDatabase | b64enc | quote }}
{{- end }}