{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "legacy-use.fullname" . }}-secrets
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.anthropicApiKey }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.apiKey }}
  api-key: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}