{{- if .Values.windows10Kubevirt.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-10-kubevirt
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-10-kubevirt
spec:
  type: {{ .Values.windows10Kubevirt.service.type }}
  ports:
    - port: {{ .Values.windows10Kubevirt.service.rdpPort }}
      targetPort: 3389
      protocol: TCP
      name: rdp
    - port: {{ .Values.windows10Kubevirt.service.vncPort }}
      targetPort: 5900
      protocol: TCP
      name: vnc
  selector:
    {{- include "legacy-use.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: windows-10-kubevirt
{{- end }}