{{- if and .Values.windows10Kubevirt.enabled .Values.windows10Kubevirt.diskUrl -}}
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-10-dv
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-10-kubevirt
spec:
  source:
    http:
      url: {{ .Values.windows10Kubevirt.diskUrl }}
  pvc:
    accessModes:
      - {{ .Values.windows10Kubevirt.persistence.accessMode }}
    {{- if .Values.windows10Kubevirt.persistence.storageClass }}
    {{- if (eq "-" .Values.windows10Kubevirt.persistence.storageClass) }}
    storageClassName: ""
    {{- else }}
    storageClassName: {{ .Values.windows10Kubevirt.persistence.storageClass | quote }}
    {{- end }}
    {{- end }}
    resources:
      requests:
        storage: {{ .Values.windows10Kubevirt.persistence.size }}
{{- end }}