{{- if and .Values.windows10Kubevirt.enabled .Values.windows10Kubevirt.ephemeralDisk -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-10-disk-template
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-10-kubevirt
spec:
  accessModes:
    - {{ .Values.windows10Kubevirt.persistence.accessMode }}
  {{- if .Values.windows10Kubevirt.persistence.storageClass }}
  {{- if (eq "-" .Values.windows10Kubevirt.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.windows10Kubevirt.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.windows10Kubevirt.persistence.size }}
  {{- if .Values.windows10Kubevirt.dataVolumeTemplate.enabled }}
  dataSource:
    name: {{ include "legacy-use.fullname" . }}-windows-10-dv
    kind: DataVolume
    apiGroup: cdi.kubevirt.io
  {{- end }}
{{- end }}