{{- if .Values.windowsXpKubevirt.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-xp-vmirs
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-xp-kubevirt
spec:
  replicas: {{ .Values.windowsXpKubevirt.replicas }}
  selector:
    matchLabels:
      {{- include "legacy-use.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: windows-xp-kubevirt
  template:
    metadata:
      labels:
        {{- include "legacy-use.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: windows-xp-kubevirt
        {{- with .Values.windowsXpKubevirt.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        kubevirt.io/disablePCIHole64: "true"
    spec:
      domain:
        machine:
          type: pc
        cpu:
          cores: {{ .Values.windowsXpKubevirt.cpu.cores }}
          model: host-passthrough
        memory:
          guest: {{ .Values.windowsXpKubevirt.memory }}
        features:
          acpi:
            enabled: true
          apic:
            enabled: true
          kvm:
            hidden: false
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
        devices:
          disks:
          - name: windows-disk
            disk:
              bus: sata
            bootOrder: 1
          interfaces:
          - name: default
            masquerade: {}
            model: rtl8139
          inputs:
          - type: tablet
            bus: usb
            name: tablet
          graphics:
          - type: vnc
            listen:
              type: socket
        resources:
          requests:
            memory: {{ .Values.windowsXpKubevirt.memory }}
            cpu: {{ .Values.windowsXpKubevirt.cpu.cores }}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: windows-disk
        {{- if .Values.windowsXpKubevirt.containerDisk }}
        containerDisk:
          image: {{ .Values.windowsXpKubevirt.containerDisk.image }}
          imagePullPolicy: {{ .Values.windowsXpKubevirt.containerDisk.pullPolicy | default "IfNotPresent" }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "legacy-use.fullname" . }}-windows-xp-pvc
        {{- end }}
      {{- with .Values.windowsXpKubevirt.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.windowsXpKubevirt.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.windowsXpKubevirt.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}