{{- if .Values.windowsKubevirt.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-vm-disk
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-kubevirt
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.windowsKubevirt.disk.storageClass }}
  {{- if (eq "-" .Values.windowsKubevirt.disk.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.windowsKubevirt.disk.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.windowsKubevirt.disk.size }}
{{- end }}