{{- if .Values.windows10Kubevirt.enabled -}}
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceReplicaSet
metadata:
  name: {{ include "legacy-use.fullname" . }}-windows-10-vmirs
  labels:
    {{- include "legacy-use.labels" . | nindent 4 }}
    app.kubernetes.io/component: windows-10-kubevirt
spec:
  replicas: {{ .Values.windows10Kubevirt.replicas }}
  selector:
    matchLabels:
      {{- include "legacy-use.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: windows-10-kubevirt
  template:
    metadata:
      labels:
        {{- include "legacy-use.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: windows-10-kubevirt
        {{- with .Values.windows10Kubevirt.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      domain:
        machine:
          type: q35
        cpu:
          cores: {{ .Values.windows10Kubevirt.cpu.cores }}
          threads: 1
          model: host-passthrough
        memory:
          guest: {{ .Values.windows10Kubevirt.memory }}
        features:
          acpi:
            enabled: true
          apic:
            enabled: true
          hyperv:
            relaxed:
              enabled: true
            vapic:
              enabled: true
            vpindex:
              enabled: true
            spinlocks:
              enabled: true
              spinlocks: 8191
            synic:
              enabled: true
            synictimer:
              enabled: true
            tlbflush:
              enabled: true
            frequencies:
              enabled: true
            reenlightenment:
              enabled: true
            ipi:
              enabled: true
            runtime:
              enabled: true
            reset:
              enabled: true
        clock:
          utc: {}
          timer:
            hpet:
              present: false
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
            hyperv: {}
        devices:
          disks:
          - name: windows-disk
            disk:
              bus: virtio
            bootOrder: 1
          interfaces:
          - name: default
            masquerade: {}
            model: virtio  # Use virtio-net-pci as in QEMU setup
          inputs:
          - type: tablet
            bus: usb
            name: tablet
          graphics:
          - type: vnc
            listen:
              type: socket
        resources:
          requests:
            memory: {{ .Values.windows10Kubevirt.memory }}
            cpu: {{ .Values.windows10Kubevirt.cpu.cores }}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: windows-disk
        {{- if .Values.windows10Kubevirt.containerDisk }}
        containerDisk:
          image: {{ .Values.windows10Kubevirt.containerDisk.image }}
          imagePullPolicy: {{ .Values.windows10Kubevirt.containerDisk.pullPolicy | default "IfNotPresent" }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "legacy-use.fullname" . }}-windows-10-pvc
        {{- end }}
      {{- with .Values.windows10Kubevirt.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.windows10Kubevirt.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.windows10Kubevirt.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}