version: '3.8'

services:
  windows-target:
    build: .
    container_name: legacy-use-windows-target
    environment:
      - VERSION=11
      - DISK_SIZE=64G
      - RAM_SIZE=4G
      - CPU_CORES=2
      - USERNAME=LegacyUser
      - PASSWORD=LegacyPass123!
      - LANGUAGE=en-US
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"    # Web viewer
      - "3389:3389"    # RDP
      - "3389:3389/udp"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    networks:
      - legacy-use-network

  # Example legacy-use session that connects to the Windows target
  legacy-use-session:
    image: legacy-use-target:local
    environment:
      - TARGET_TYPE=rdp
      - TARGET_HOST=windows-target
      - TARGET_PORT=3389
      - TARGET_USERNAME=LegacyUser
      - TARGET_PASSWORD=LegacyPass123!
    depends_on:
      - windows-target
    networks:
      - legacy-use-network

volumes:
  windows_data:

networks:
  legacy-use-network:
    driver: bridge