# Production values for legacy-use
# This overrides values in values.yaml to use GitHub Container Registry images

backend:
  image:
    repository: ghcr.io/johannhartmann/legacy-use-backend
    pullPolicy: Always
    tag: main  # This will be updated by CI/CD

frontend:
  image:
    repository: ghcr.io/johannhartmann/legacy-use-frontend
    pullPolicy: Always
    tag: main  # This will be updated by CI/CD

# Wine Target Configuration
wineTarget:
  enabled: false  # Set to true to enable Wine container
  image:
    repository: ghcr.io/johannhartmann/legacy-use-wine-target
    pullPolicy: Always
    tag: main

# Linux Target Configuration
linuxTarget:
  enabled: false  # Set to true to enable Linux target
  image:
    repository: ghcr.io/johannhartmann/legacy-use-linux-machine
    pullPolicy: Always
    tag: main

# Update ingress for your production domain
ingress:
  enabled: true
  className: "nginx"  # Update based on your ingress controller
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # If using cert-manager
  hosts:
    - host: legacy-use.example.com  # Update with your domain
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: frontend
              port:
                number: 80
        - path: /api
          pathType: ImplementationSpecific
          backend:
            service:
              name: backend
              port:
                number: 8088
  tls:
    - secretName: legacy-use-tls
      hosts:
        - legacy-use.example.com  # Update with your domain