# Container disk for macOS OVMF CODE
FROM scratch

# Copy OVMF_CODE.fd from the vms/macos-mojave folder
COPY OVMF_CODE.fd /disk/

# Set the correct label for KubeVirt container disk
LABEL kubevirt.io/images.path=/disk